project_id = "trustedbums"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:8080/trustedbums"
additional_redirect_urls = [
  "https://pidpoddev.github.io/trustedbums/login",
  "https://trustedbums.com/login"
]

[auth.third_party.clerk]
enabled = true
domain = "gorgeous-kit-53.accounts.dev"

[functions.schedule-teams-meeting]
verify_jwt = false

[functions.send-website-email]
verify_jwt = false

[functions.send-admin-email]
verify_jwt = false

[functions.email-track]
verify_jwt = false

[functions.invite-bum]
verify_jwt = false

[functions.sync-teams-attendees]
verify_jwt = false
