create unique index if not exists admin_scrum_items_source_key_unique_idx
  on public.admin_scrum_items (source_key)
  nulls distinct;

insert into public.admin_scrum_items (
  source_key,
  title,
  description,
  status,
  priority,
  item_type,
  source,
  related_area,
  owner_label,
  added_by_agent,
  github_commit,
  github_run_id,
  evidence_links,
  closure_note,
  closed_at
) values
  (
    'git:9f42bf4',
    'Restore Client marketing copy',
    'Restored the prior Client-focused public landing message while keeping the new separate Bum landing page.',
    'CLOSED',
    'P1',
    'TASK',
    'Lead Dev',
    'Public website',
    'Lead Eng',
    'Lead Developer',
    '9f42bf4',
    null,
    array['git:9f42bf4', 'docs/codex-edit-log.md'],
    'Merged to main as 9f42bf4 after local verification and hosted deploy/smoke evidence.',
    now()
  ),
  (
    'git:0ee2f44',
    'Split public Client and Bum landing pages',
    'Created a Client-first main landing page and a separate /bums landing page with role-locked signup intent.',
    'CLOSED',
    'P1',
    'TASK',
    'Lead Dev',
    'Public website',
    'Lead Eng',
    'Lead Developer',
    '0ee2f44',
    null,
    array['git:0ee2f44', 'src/pages/BumLanding.tsx', 'src/components/SignupIntentDialog.tsx'],
    'Merged to main as 0ee2f44.',
    now()
  ),
  (
    'git:41187e0',
    'Add RLS coverage requirements to agents',
    'Updated agent rules so new Supabase/RLS/data-workflow changes require positive and negative authorization coverage.',
    'CLOSED',
    'P1',
    'SECURITY',
    'Security',
    'Agent operating rules',
    'Lead Eng',
    'Lead Developer',
    '41187e0',
    null,
    array['git:41187e0', 'docs/agents/company-wide-rules.md', 'docs/agents/business-access-rules.md'],
    'Merged to main as 41187e0.',
    now()
  ),
  (
    'git:73f0b06',
    'Write customer targets with minimal return',
    'Changed customer-target writes to avoid returning rows when RLS read policies can block an otherwise valid mutation.',
    'CLOSED',
    'P0',
    'BUG',
    'Lead Dev',
    'Client targets / RLS',
    'Lead Eng',
    'Lead Developer',
    '73f0b06',
    null,
    array['git:73f0b06', 'src/lib/portalApi.ts', 'src/test/customerTargetRules.test.ts'],
    'Merged to main as 73f0b06 and used as the latest fully green product-code head in release docs.',
    now()
  ),
  (
    'git:7609b0d',
    'Avoid target create returning read under RLS',
    'Removed a create/read coupling that could fail under production RLS token behavior.',
    'CLOSED',
    'P0',
    'BUG',
    'Lead Dev',
    'Client targets / RLS',
    'Lead Eng',
    'Lead Developer',
    '7609b0d',
    null,
    array['git:7609b0d', 'src/lib/portalApi.ts', 'src/test/customerTargetRules.test.ts'],
    'Merged to main as 7609b0d.',
    now()
  ),
  (
    'git:5c6d451',
    'Stabilize go-live target creation QA',
    'Added target-creator read policy coverage and adjusted go-live target creation checks.',
    'CLOSED',
    'P0',
    'QA',
    'QA',
    'Go-live QA / customer targets',
    'QA Test Engineer',
    'QA Test Engineer',
    '5c6d451',
    null,
    array['git:5c6d451', 'tests/e2e/go-live-client-bum-workflow.spec.ts', 'supabase/migrations/20260608202500_allow_target_creators_to_read_created_targets.sql'],
    'Merged to main as 5c6d451.',
    now()
  ),
  (
    'git:ce8369d',
    'Allow signed-in session tokens for target creation',
    'Adjusted Supabase token handling and policies for Clerk session token shape used by production RLS paths.',
    'CLOSED',
    'P0',
    'SECURITY',
    'Security',
    'Auth / RLS',
    'Security Engineer',
    'Security Engineer',
    'ce8369d',
    null,
    array['git:ce8369d', 'src/test/supabaseTokenMode.test.ts', 'supabase/migrations/20260608201500_allow_signed_in_session_tokens_for_target_creation.sql'],
    'Merged to main as ce8369d.',
    now()
  ),
  (
    'git:4dfcb30',
    'Use Supabase JWT template for RLS data calls',
    'Aligned frontend Supabase data calls with the Clerk/Supabase JWT template expected by RLS-sensitive flows.',
    'CLOSED',
    'P0',
    'SECURITY',
    'Security',
    'Auth / RLS',
    'Security Engineer',
    'Security Engineer',
    '4dfcb30',
    null,
    array['git:4dfcb30', 'src/lib/supabase.ts', 'src/test/supabaseTokenMode.test.ts'],
    'Merged to main as 4dfcb30.',
    now()
  ),
  (
    'git:10fd8ca',
    'Add Client and Bum go-live workflow gate',
    'Added the hosted go-live workflow gate for Client and Bum journeys.',
    'CLOSED',
    'P1',
    'QA',
    'QA',
    'Go-live QA',
    'QA Test Engineer',
    'QA Test Engineer',
    '10fd8ca',
    null,
    array['git:10fd8ca', 'tests/e2e/go-live-client-bum-workflow.spec.ts', 'docs/production-go-live.md'],
    'Merged to main as 10fd8ca.',
    now()
  ),
  (
    'git:b1928cc',
    'Add QA authorization cleanup guard',
    'Added deterministic cleanup support for QA authorization fixture data.',
    'CLOSED',
    'P1',
    'QA',
    'QA',
    'Authorization fixtures',
    'QA Harness Reliability',
    'QA Harness Reliability Agent',
    'b1928cc',
    null,
    array['git:b1928cc', 'supabase/qa_authorization_cleanup.sql', 'src/test/qaAuthorizationFixtures.test.ts'],
    'Merged to main as b1928cc.',
    now()
  ),
  (
    'git:fc1888c',
    'Add QA authorization fixtures',
    'Added deterministic multi-role authorization fixtures and fixture documentation for seeded allow/deny checks.',
    'CLOSED',
    'P1',
    'QA',
    'QA',
    'Authorization fixtures',
    'QA Harness Reliability',
    'QA Harness Reliability Agent',
    'fc1888c',
    null,
    array['git:fc1888c', 'supabase/qa_authorization_seed.sql', 'docs/qa-authorization-fixtures.md'],
    'Merged to main as fc1888c.',
    now()
  ),
  (
    'git:28ca4b6',
    'Resolve access review backlog item',
    'Closed the admin access review workflow backlog item with regression coverage.',
    'CLOSED',
    'P2',
    'TASK',
    'Product Ops',
    'Admin access review',
    'Product Ops',
    'Product Ops Agent',
    '28ca4b6',
    null,
    array['git:28ca4b6', 'src/test/adminAccessReviewWorkflow.test.ts', 'docs/product-ops-workflow-backlog.md'],
    'Merged to main as 28ca4b6.',
    now()
  ),
  (
    'git:3ddc2d7',
    'Extend hosted preflight fetch retries',
    'Made hosted QA target preflight more reliable by retrying app-shell fetches.',
    'CLOSED',
    'P1',
    'QA',
    'QA',
    'QA harness',
    'QA Harness Reliability',
    'QA Harness Reliability Agent',
    '3ddc2d7',
    null,
    array['git:3ddc2d7', 'scripts/qa-target-preflight.mjs', 'src/test/qaTargetPreflight.test.ts'],
    'Merged to main as 3ddc2d7.',
    now()
  ),
  (
    'git:89d8339',
    'Stabilize visual audit empty states',
    'Improved Visual UI Audit reliability around empty states.',
    'CLOSED',
    'P1',
    'QA',
    'QA',
    'Visual QA',
    'QA Harness Reliability',
    'QA Harness Reliability Agent',
    '89d8339',
    null,
    array['git:89d8339', '.github/workflows/visual-ui-audit.yml', 'tests/e2e/visual-ui-audit.spec.ts'],
    'Merged to main as 89d8339.',
    now()
  ),
  (
    'git:b453a48',
    'Handle blank Supabase function URL in contact smoke',
    'Prevented contact-intake smoke from failing on blank function URL configuration.',
    'CLOSED',
    'P2',
    'QA',
    'QA',
    'Contact intake smoke',
    'QA Harness Reliability',
    'QA Harness Reliability Agent',
    'b453a48',
    null,
    array['git:b453a48', 'tests/e2e/contact-intake.spec.ts'],
    'Merged to main as b453a48.',
    now()
  ),
  (
    'git:645d3c6',
    'Complete scrum hardening batch',
    'Closed the earlier scrum hardening batch covering metadata, headers, handoff signals, raw extension capture scoping, and dependency cleanup.',
    'CLOSED',
    'P1',
    'SECURITY',
    'Security',
    'Scrum hardening',
    'Lead Eng',
    'Lead Developer',
    '645d3c6',
    null,
    array['git:645d3c6', 'src/test/scrumQueueRegression.test.ts', 'supabase/migrations/20260608141000_limit_raw_extension_capture_reads.sql'],
    'Merged to main as 645d3c6.',
    now()
  ),
  (
    'open:qa-current-head-workflow-rerun',
    'Restore QA backlog/test contract and rerun current-head QA',
    'GitHub QA run 27178512695 failed because scrumQueueRegression still requires seeded-proof QA backlog sections. Local hotfix proof is green after restoring the sections, but GitHub QA needs a current-head rerun.',
    'OPEN',
    'P1',
    'BUG',
    'QA',
    'Release QA',
    'Lead Eng',
    'QA Test Engineer',
    null,
    '27178512695',
    array['docs/qa-test-backlog.md', 'docs/lead-developer-recommendations.md', 'src/test/scrumQueueRegression.test.ts', 'GitHub QA run 27178512695'],
    null,
    null
  ),
  (
    'open:visual-ui-audit-current-head',
    'Run current-head Visual UI Audit for landing split and copy restore',
    'The latest visual artifact is still run 27167324836 on 441fd92, which is stale for 0ee2f44 and 9f42bf4 public landing changes.',
    'OPEN',
    'P1',
    'QA',
    'QA',
    'Visual QA / public website',
    'QA Harness Reliability',
    'QA Harness Reliability Agent',
    null,
    '27167324836',
    array['docs/qa-test-backlog.md', 'docs/release-verification-backlog.md', 'GitHub Visual UI Audit run 27167324836'],
    null,
    null
  ),
  (
    'open:exact-head-code-review',
    'Refresh exact-head Code Review state',
    'The current Code Review marker points at c9b7b07, not current head 9f42bf4 or its successor.',
    'OPEN',
    'P1',
    'RELEASE',
    'Lead Dev',
    'Code review / release gate',
    'Code Review Agent',
    'Release Verification Agent',
    null,
    null,
    array['docs/release-verification-backlog.md', '.codex-review-decision.json'],
    null,
    null
  ),
  (
    'open:customer-target-seeded-allow-deny',
    'Add seeded allow/deny proof for customer target create and reads',
    'Customer-target route smoke is green, but direct seeded role allow/deny proof remains missing for same-company allow, finance deny, cross-company deny, Bum deny, and Admin rescue.',
    'OPEN',
    'P1',
    'QA',
    'QA',
    'Customer targets / RLS',
    'QA Test Engineer',
    'QA Test Engineer',
    null,
    null,
    array['docs/qa-test-backlog.md', 'supabase/qa_authorization_seed.sql', 'src/test/customerTargetRules.test.ts'],
    null,
    null
  ),
  (
    'open:go-live-client-bum-gate',
    'Run Client/Bum go-live workflow gate before external launch',
    'qa:go-live exists but was not rerun in the latest release handoff; it should pass against hosted QA before external launch.',
    'OPEN',
    'P1',
    'QA',
    'QA',
    'Go-live QA',
    'QA Test Engineer',
    'QA Test Engineer',
    null,
    null,
    array['docs/qa-test-backlog.md', 'tests/e2e/go-live-client-bum-workflow.spec.ts'],
    null,
    null
  ),
  (
    'open:service-role-seeded-authorization',
    'Add seeded allow/deny tests for service-role authorization paths',
    'Authorization-sensitive verify_jwt=false functions have source-level regression coverage, but live/API seeded allow/deny coverage is still missing for first-domain claim, public-email review, same-domain approval, cross-company denial, direct auth-field mutation denial, and valid invite handoff.',
    'OPEN',
    'P1',
    'SECURITY',
    'Security',
    'Service-role edge functions',
    'Security Engineer',
    'Security Engineer',
    null,
    null,
    array['docs/security-review-backlog.md', 'src/test/serviceRoleAuthorization.test.ts', 'supabase/qa_authorization_seed.sql'],
    null,
    null
  ),
  (
    'open:supabase-leaked-password-protection',
    'Enable Supabase Auth leaked-password protection',
    'Supabase security advisors still report auth_leaked_password_protection. Dashboard save is blocked because HaveIBeenPwned leaked password protection requires a Pro plan.',
    'BLOCKED',
    'P1',
    'SECURITY',
    'Security',
    'Supabase Auth',
    'Supabase Admin',
    'Security Engineer',
    null,
    null,
    array['docs/security-review-backlog.md', 'Supabase security advisor: auth_leaked_password_protection'],
    null,
    null
  ),
  (
    'open:external-dns-tls-rcdl',
    'Fix external DNS TLS path for rcdl.tplinkdns.com',
    'https://rcdl.tplinkdns.com still fails TLS verification from this runner, so release proof remains anchored to trustedbums.com.',
    'OPEN',
    'P2',
    'INFRA',
    'Release',
    'External DNS / TLS',
    'Infrastructure',
    'Release Verification Agent',
    null,
    null,
    array['docs/release-verification-backlog.md', 'docs/lead-developer-recommendations.md'],
    null,
    null
  ),
  (
    'open:email-track-valid-delivery-click-proof',
    'Add valid-delivery email-track click proof',
    'email-track hardening is live, but one safe seeded valid-delivery allowed redirect that records a click remains as release smoke proof.',
    'OPEN',
    'P2',
    'SECURITY',
    'Security',
    'Email tracking',
    'Security Engineer',
    'Security Engineer',
    null,
    null,
    array['docs/security-review-backlog.md'],
    null,
    null
  ),
  (
    'open:valid-invite-smoke',
    'Add safe authenticated invite smoke for approved redirect handoff',
    'Client Team and Bum invitation redirect hardening is live, but one valid invite smoke remains as post-release proof.',
    'OPEN',
    'P2',
    'QA',
    'QA',
    'Invitations / redirects',
    'QA Test Engineer',
    'Security Engineer',
    null,
    null,
    array['docs/security-review-backlog.md'],
    null,
    null
  ),
  (
    'open:deployment-provenance-ledger',
    'Add deployment provenance by migration and function revision',
    'Deployment provenance by migration/function revision is still missing; prior function drift is resolved, but CI summaries do not clearly map live function versions to workflow/change tickets.',
    'OPEN',
    'P2',
    'RELEASE',
    'Release',
    'Deployment provenance',
    'Release Verification',
    'Release Verification Agent',
    null,
    null,
    array['docs/security-review-backlog.md', 'docs/release-verification-backlog.md'],
    null,
    null
  )
on conflict (source_key) where source_key is not null do update set
  title = excluded.title,
  description = excluded.description,
  status = excluded.status,
  priority = excluded.priority,
  item_type = excluded.item_type,
  source = excluded.source,
  related_area = excluded.related_area,
  owner_label = excluded.owner_label,
  added_by_agent = excluded.added_by_agent,
  github_commit = excluded.github_commit,
  github_run_id = excluded.github_run_id,
  evidence_links = excluded.evidence_links,
  closure_note = excluded.closure_note,
  closed_at = excluded.closed_at,
  updated_at = now();
