insert into public.admin_scrum_items (
  source_key,
  tracking_number,
  title,
  description,
  status,
  priority,
  item_type,
  source,
  related_area,
  owner_label,
  added_by_agent,
  github_commit,
  github_run_id,
  evidence_links,
  closure_note,
  closed_at
) values
  (
    'backlog:accessibility:mobile-sidebar-accessible-name',
    29,
    'Give the mobile portal sidebar an accessible name and a visible dismiss control',
    'Backfilled from active specialist backlog recommendation: Give the mobile portal sidebar an accessible name and a visible dismiss control.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'Accessibility',
    'Accessibility Specialist',
    'Accessibility Specialist',
    null,
    null,
    array['docs/accessibility-backlog.md'],
    null,
    null
  ),
  (
    'backlog:accessibility:signup-dialog-error-labeling',
    30,
    'Add programmatic error state and group labeling to the public sign-up intent dialog',
    'Backfilled from active specialist backlog recommendation: Add programmatic error state and group labeling to the public sign-up intent dialog.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'Accessibility',
    'Accessibility Specialist',
    'Accessibility Specialist',
    null,
    null,
    array['docs/accessibility-backlog.md'],
    null,
    null
  ),
  (
    'backlog:accessibility:admin-scrum-control-labels',
    31,
    'Give the admin scrum tracker search and select controls programmatic labels',
    'Backfilled from active specialist backlog recommendation: Give the admin scrum tracker search and select controls programmatic labels.',
    'OPEN',
    'P2',
    'TASK',
    'Other',
    'Accessibility / Admin Scrum',
    'Accessibility Specialist',
    'Accessibility Specialist',
    null,
    null,
    array['docs/accessibility-backlog.md', 'src/pages/admin/AdminScrumTracker.tsx'],
    null,
    null
  ),
  (
    'backlog:accessibility:privacy-launcher-target-size',
    32,
    'Enlarge the collapsed Privacy choices launcher to meet WCAG 2.2 target-size expectations',
    'Backfilled from active specialist backlog recommendation: Enlarge the collapsed Privacy choices launcher to meet WCAG 2.2 target-size expectations.',
    'OPEN',
    'P2',
    'TASK',
    'Other',
    'Accessibility / Privacy',
    'Accessibility Specialist',
    'Accessibility Specialist',
    null,
    null,
    array['docs/accessibility-backlog.md'],
    null,
    null
  ),
  (
    'backlog:agent-ops:first-automation-prompt-sync-audit',
    33,
    'First automation and prompt synchronization audit pending',
    'Backfilled from active specialist backlog recommendation: First automation and prompt synchronization audit pending.',
    'OPEN',
    'P1',
    'DOCS',
    'Other',
    'Agent operations',
    'Agent Operations Steward',
    'Weekly Agent Operations Steward',
    null,
    null,
    array['docs/agent-operations-backlog.md'],
    null,
    null
  ),
  (
    'backlog:b2b-growth:client-intake-qualification',
    34,
    'Enrich the Client intake path and operationalize qualification',
    'Backfilled from active specialist backlog recommendation: Enrich the Client intake path and operationalize qualification.',
    'OPEN',
    'P0',
    'TASK',
    'Other',
    'B2B growth',
    'B2B Growth Consultant',
    'B2B Growth Consultant',
    null,
    null,
    array['docs/b2b-marketing-growth-backlog.md'],
    null,
    null
  ),
  (
    'backlog:b2b-growth:claim-safe-proof-spine',
    35,
    'Build a claim-safe proof spine before scaling demand',
    'Backfilled from active specialist backlog recommendation: Build a claim-safe proof spine before scaling demand.',
    'OPEN',
    'P0',
    'TASK',
    'Other',
    'B2B growth / Trust',
    'B2B Growth Consultant',
    'B2B Growth Consultant',
    null,
    null,
    array['docs/b2b-marketing-growth-backlog.md'],
    null,
    null
  ),
  (
    'backlog:b2b-growth:investor-advisor-referrals',
    36,
    'Make investor, advisor, and operator referrals the primary Client-demand motion',
    'Backfilled from active specialist backlog recommendation: Make investor, advisor, and operator referrals the primary Client-demand motion.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'B2B growth',
    'B2B Growth Consultant',
    'B2B Growth Consultant',
    null,
    null,
    array['docs/b2b-marketing-growth-backlog.md'],
    null,
    null
  ),
  (
    'backlog:b2b-growth:founder-led-linkedin',
    37,
    'Run founder-led LinkedIn around hard-account access and trust validation',
    'Backfilled from active specialist backlog recommendation: Run founder-led LinkedIn around hard-account access and trust validation.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'B2B growth',
    'B2B Growth Consultant',
    'B2B Growth Consultant',
    null,
    null,
    array['docs/b2b-marketing-growth-backlog.md'],
    null,
    null
  ),
  (
    'backlog:b2b-growth:invite-only-bum-recruiting',
    38,
    'Keep Bum recruiting invite-only and referral-scored',
    'Backfilled from active specialist backlog recommendation: Keep Bum recruiting invite-only and referral-scored.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'Bum recruiting',
    'B2B Growth Consultant',
    'B2B Growth Consultant',
    null,
    null,
    array['docs/b2b-marketing-growth-backlog.md'],
    null,
    null
  ),
  (
    'backlog:b2b-growth:manual-nurture-objection-logging',
    39,
    'Build manual nurture and objection logging before any lifecycle automation',
    'Backfilled from active specialist backlog recommendation: Build manual nurture and objection logging before any lifecycle automation.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'B2B growth / CRM',
    'B2B Growth Consultant',
    'B2B Growth Consultant',
    null,
    null,
    array['docs/b2b-marketing-growth-backlog.md'],
    null,
    null
  ),
  (
    'backlog:content:prospects-to-client-prospects',
    40,
    'Rename the Bum-side company workflow from Prospects to Client Prospects',
    'Backfilled from active specialist backlog recommendation: Rename the Bum-side company workflow from Prospects to Client Prospects.',
    'OPEN',
    'P1',
    'DOCS',
    'Other',
    'Content / Bum portal',
    'Content Copyeditor',
    'Content Copyeditor',
    null,
    null,
    array['docs/content-copyeditor-backlog.md'],
    null,
    null
  ),
  (
    'backlog:content:replace-bum-prospect-term',
    41,
    'Replace Bum Prospect with a recruiting-specific person term',
    'Backfilled from active specialist backlog recommendation: Replace Bum Prospect with a recruiting-specific person term.',
    'OPEN',
    'P1',
    'DOCS',
    'Other',
    'Content / Recruiting',
    'Content Copyeditor',
    'Content Copyeditor',
    null,
    null,
    array['docs/content-copyeditor-backlog.md'],
    null,
    null
  ),
  (
    'backlog:content:client-agreement-terminology',
    42,
    'Finish the Client Agreement terminology cleanup and retire legacy Partner Terms',
    'Backfilled from active specialist backlog recommendation: Finish the Client Agreement terminology cleanup and retire legacy Partner Terms.',
    'OPEN',
    'P1',
    'DOCS',
    'Other',
    'Content / Legal terminology',
    'Content Copyeditor',
    'Content Copyeditor',
    null,
    null,
    array['docs/content-copyeditor-backlog.md'],
    null,
    null
  ),
  (
    'backlog:content:bum-intro-requests-copy',
    43,
    'Keep Bum Intro Requests explicit in the client request-history helper copy',
    'Backfilled from active specialist backlog recommendation: Keep Bum Intro Requests explicit in the client request-history helper copy.',
    'OPEN',
    'P2',
    'DOCS',
    'Other',
    'Content / Client requests',
    'Content Copyeditor',
    'Content Copyeditor',
    null,
    null,
    array['docs/content-copyeditor-backlog.md'],
    null,
    null
  ),
  (
    'backlog:data:client-finance-read-model',
    44,
    'Split Client Finance reporting into a finance-safe read model',
    'Backfilled from active specialist backlog recommendation: Split Client Finance reporting into a finance-safe read model.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'Data / Client Finance',
    'Data Analytics Engineer',
    'Data Analytics Engineer',
    null,
    null,
    array['docs/data-analytics-backlog.md'],
    null,
    null
  ),
  (
    'backlog:data:admin-email-reporting-access-rule',
    45,
    'Add an explicit admin-email reporting access rule',
    'Backfilled from active specialist backlog recommendation: Add an explicit admin-email reporting access rule.',
    'OPEN',
    'P1',
    'DOCS',
    'Other',
    'Data / Admin email',
    'Data Analytics Engineer',
    'Data Analytics Engineer',
    null,
    null,
    array['docs/data-analytics-backlog.md', 'docs/business-access-rules.md'],
    null,
    null
  ),
  (
    'backlog:data:admin-email-aggregate-metrics',
    46,
    'Make admin email metrics aggregate-first and stop treating opens as decision-grade',
    'Backfilled from active specialist backlog recommendation: Make admin email metrics aggregate-first and stop treating opens as decision-grade.',
    'OPEN',
    'P2',
    'TASK',
    'Other',
    'Data / Admin email',
    'Data Analytics Engineer',
    'Data Analytics Engineer',
    null,
    null,
    array['docs/data-analytics-backlog.md'],
    null,
    null
  ),
  (
    'backlog:performance:server-scoped-summaries',
    47,
    'Replace whole-list dashboard, report, and export loading with server-scoped summaries and bounded reads',
    'Backfilled from active specialist backlog recommendation: Replace whole-list dashboard, report, and export loading with server-scoped summaries and bounded reads.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'Performance / Portal data',
    'Performance Engineer',
    'Performance Engineer',
    null,
    null,
    array['docs/performance-engineering-backlog.md'],
    null,
    null
  ),
  (
    'backlog:performance:portal-search-large-datasets',
    48,
    'Stop portal search from warming large multi-query datasets in persistent chrome',
    'Backfilled from active specialist backlog recommendation: Stop portal search from warming large multi-query datasets in persistent chrome.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'Performance / Portal search',
    'Performance Engineer',
    'Performance Engineer',
    null,
    null,
    array['docs/performance-engineering-backlog.md'],
    null,
    null
  ),
  (
    'backlog:performance:admin-table-index-debt',
    49,
    'Clear advisor-backed index debt on newly active admin tables before the admin scrum queue grows',
    'Backfilled from active specialist backlog recommendation: Clear advisor-backed index debt on newly active admin tables before the admin scrum queue grows.',
    'OPEN',
    'P2',
    'TASK',
    'Other',
    'Performance / Supabase indexes',
    'Performance Engineer',
    'Performance Engineer',
    null,
    null,
    array['docs/performance-engineering-backlog.md', 'src/pages/admin/AdminScrumTracker.tsx'],
    null,
    null
  ),
  (
    'backlog:performance:authenticated-timing-proof',
    50,
    'Capture authenticated timing proof for aggregate telemetry routes now that local 8080 preview is available again',
    'Backfilled from active specialist backlog recommendation: Capture authenticated timing proof for aggregate telemetry routes now that local 8080 preview is available again.',
    'OPEN',
    'P2',
    'QA',
    'Other',
    'Performance / Telemetry',
    'Performance Engineer',
    'Performance Engineer',
    null,
    null,
    array['docs/performance-engineering-backlog.md'],
    null,
    null
  ),
  (
    'backlog:product-ops:handoff-triage-editable-aging',
    51,
    'Make handoff triage editable and age work by last operator action, not only by create time',
    'Backfilled from active specialist backlog recommendation: Make handoff triage editable and age work by last operator action, not only by create time.',
    'OPEN',
    'P1',
    'TASK',
    'Product Ops',
    'Product Ops / Handoffs',
    'Product Ops',
    'Product Ops Agent',
    null,
    null,
    array['docs/product-ops-workflow-backlog.md'],
    null,
    null
  ),
  (
    'backlog:product-ops:finance-exception-lanes',
    52,
    'Add explicit finance exception lanes and note capture across payment reports, invoices, and payouts',
    'Backfilled from active specialist backlog recommendation: Add explicit finance exception lanes and note capture across payment reports, invoices, and payouts.',
    'OPEN',
    'P1',
    'TASK',
    'Product Ops',
    'Product Ops / Finance',
    'Product Ops',
    'Product Ops Agent',
    null,
    null,
    array['docs/product-ops-workflow-backlog.md'],
    null,
    null
  ),
  (
    'backlog:product-ops:admin-scrum-proof-backed-closeout',
    53,
    'Require proof-backed closeout and audit history in the new admin scrum tracker',
    'Backfilled from active specialist backlog recommendation: Require proof-backed closeout and audit history in the new admin scrum tracker.',
    'OPEN',
    'P1',
    'TASK',
    'Product Ops',
    'Product Ops / Admin Scrum',
    'Product Ops',
    'Product Ops Agent',
    null,
    null,
    array['docs/product-ops-workflow-backlog.md', 'src/pages/admin/AdminScrumTracker.tsx'],
    null,
    null
  ),
  (
    'backlog:qa-harness:preflight-artifact-location',
    54,
    'Move qa-target-preflight artifacts out of Playwright test-results root',
    'Backfilled from active specialist backlog recommendation: Move qa-target-preflight artifacts out of Playwright test-results root.',
    'OPEN',
    'P1',
    'QA',
    'QA',
    'QA harness',
    'QA Harness Reliability',
    'QA Harness Reliability Agent',
    null,
    null,
    array['docs/qa-harness-reliability-backlog.md', 'scripts/qa-target-preflight.mjs'],
    null,
    null
  ),
  (
    'backlog:qa-harness:raw-sourced-hosted-env-states',
    55,
    'Keep raw-shell, sourced .env.qa, and hosted workflow env states separate in every handoff',
    'Backfilled from active specialist backlog recommendation: Keep raw-shell, sourced .env.qa, and hosted workflow env states separate in every handoff.',
    'OPEN',
    'P2',
    'QA',
    'QA',
    'QA harness',
    'QA Harness Reliability',
    'QA Harness Reliability Agent',
    null,
    null,
    array['docs/qa-harness-reliability-backlog.md'],
    null,
    null
  ),
  (
    'backlog:security:admin-scrum-server-owned-audit-actors',
    56,
    'Move admin scrum tracker audit actors to a server-owned path',
    'Backfilled from active specialist backlog recommendation: Move admin scrum tracker audit actors to a server-owned path.',
    'OPEN',
    'P1',
    'SECURITY',
    'Security',
    'Admin Scrum / Audit',
    'Security Engineer',
    'Security Engineer',
    null,
    null,
    array['docs/security-review-backlog.md', 'src/pages/admin/AdminScrumTracker.tsx'],
    null,
    null
  ),
  (
    'backlog:trust:dmarc-mailbox-review',
    57,
    'Run a current mailbox-backed DMARC review and prepare DMARC enforcement',
    'Backfilled from active specialist backlog recommendation: Run a current mailbox-backed DMARC review and prepare DMARC enforcement.',
    'OPEN',
    'P1',
    'SECURITY',
    'Other',
    'Trust / Email',
    'Trust & Reputation Consultant',
    'Trust & Reputation Consultant',
    null,
    null,
    array['docs/trust-reputation-backlog.md', 'docs/dmarc-report-review.md'],
    null,
    null
  ),
  (
    'backlog:trust:route-specific-initial-metadata',
    58,
    'Serve route-specific metadata in the initial HTML response for public trust routes',
    'Backfilled from active specialist backlog recommendation: Serve route-specific metadata in the initial HTML response for public trust routes.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'Trust / Public website',
    'Trust & Reputation Consultant',
    'Trust & Reputation Consultant',
    null,
    null,
    array['docs/trust-reputation-backlog.md'],
    null,
    null
  ),
  (
    'backlog:trust:remove-public-extension-zip',
    59,
    'Remove the public pre-store extension zip until permissions are narrowed',
    'Backfilled from active specialist backlog recommendation: Remove the public pre-store extension zip until permissions are narrowed.',
    'OPEN',
    'P1',
    'SECURITY',
    'Other',
    'Trust / Chrome extension',
    'Trust & Reputation Consultant',
    'Trust & Reputation Consultant',
    null,
    null,
    array['docs/trust-reputation-backlog.md', 'docs/chrome-extension.md'],
    null,
    null
  ),
  (
    'backlog:ui:coordinated-mobile-utility-rail',
    60,
    'Replace competing fixed utilities with one coordinated mobile utility rail',
    'Backfilled from active specialist backlog recommendation: Replace competing fixed utilities with one coordinated mobile utility rail.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'UI / Mobile utilities',
    'UI Consultant',
    'UI Consultant',
    null,
    null,
    array['docs/ui-optimization-backlog.md'],
    null,
    null
  ),
  (
    'backlog:ui:mobile-reports-progressive-disclosure',
    61,
    'Turn mobile reports into progressive disclosure instead of a full control stack',
    'Backfilled from active specialist backlog recommendation: Turn mobile reports into progressive disclosure instead of a full control stack.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'UI / Mobile reports',
    'UI Consultant',
    'UI Consultant',
    null,
    null,
    array['docs/ui-optimization-backlog.md'],
    null,
    null
  ),
  (
    'backlog:ui:privacy-legal-mobile-trust-navigation',
    62,
    'Rebuild privacy and legal mobile controls as trust navigation, not micro-utilities',
    'Backfilled from active specialist backlog recommendation: Rebuild privacy and legal mobile controls as trust navigation, not micro-utilities.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'UI / Trust navigation',
    'UI Consultant',
    'UI Consultant',
    null,
    null,
    array['docs/ui-optimization-backlog.md'],
    null,
    null
  ),
  (
    'backlog:ui:responsive-admin-queue-cards',
    63,
    'Replace narrow-screen admin tables with responsive queue cards, and add hosted visual coverage for the new route pair',
    'Backfilled from active specialist backlog recommendation: Replace narrow-screen admin tables with responsive queue cards, and add hosted visual coverage for the new route pair.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'UI / Admin responsive',
    'UI Consultant',
    'UI Consultant',
    null,
    null,
    array['docs/ui-optimization-backlog.md', 'src/pages/admin/AdminScrumTracker.tsx'],
    null,
    null
  ),
  (
    'backlog:ux:client-only-signup-cta-labels',
    64,
    'Make the client-only signup CTA labels explicit across /',
    'Backfilled from active specialist backlog recommendation: Make the client-only signup CTA labels explicit across /.',
    'OPEN',
    'P1',
    'TASK',
    'Other',
    'UX / Public website',
    'UX Consultant',
    'UX Consultant',
    null,
    null,
    array['docs/ux-optimization-backlog.md', 'src/pages/Index.tsx'],
    null,
    null
  ),
  (
    'backlog:ux:mobile-consent-banner-footprint',
    65,
    'Reduce the first-layer consent banner footprint on mobile',
    'Backfilled from active specialist backlog recommendation: Reduce the first-layer consent banner footprint on mobile.',
    'OPEN',
    'P2',
    'TASK',
    'Other',
    'UX / Consent',
    'UX Consultant',
    'UX Consultant',
    null,
    null,
    array['docs/ux-optimization-backlog.md'],
    null,
    null
  )
on conflict (source_key) where source_key is not null do update set
  title = excluded.title,
  description = excluded.description,
  status = excluded.status,
  priority = excluded.priority,
  item_type = excluded.item_type,
  source = excluded.source,
  related_area = excluded.related_area,
  owner_label = excluded.owner_label,
  added_by_agent = excluded.added_by_agent,
  github_commit = excluded.github_commit,
  github_run_id = excluded.github_run_id,
  evidence_links = excluded.evidence_links,
  closure_note = excluded.closure_note,
  closed_at = excluded.closed_at,
  updated_at = now();

select setval(pg_get_serial_sequence('public.admin_scrum_items', 'tracking_number'), (select max(tracking_number) from public.admin_scrum_items));
