create table if not exists public.admin_scrum_items (
  id uuid primary key default gen_random_uuid(),
  tracking_number bigint generated by default as identity,
  tracking_id text generated always as ('TB-' || lpad(tracking_number::text, 4, '0')) stored unique,
  title text not null check (length(trim(title)) > 0),
  description text not null default '',
  status text not null default 'OPEN' check (status in ('OPEN', 'IN_PROGRESS', 'BLOCKED', 'FIXED', 'CLOSED', 'WONT_FIX')),
  priority text not null default 'P2' check (priority in ('P0', 'P1', 'P2', 'P3')),
  source text not null default 'Scrum' check (source in ('Scrum', 'QA', 'Security', 'Lead Dev', 'Release', 'User', 'Product Ops', 'Other')),
  related_area text,
  owner_label text,
  github_commit text,
  github_run_id text,
  evidence_links text[] not null default '{}',
  closure_note text,
  created_by text references public.profiles(id) on delete set null,
  updated_by text references public.profiles(id) on delete set null,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists admin_scrum_items_status_priority_idx
  on public.admin_scrum_items (status, priority, created_at desc);

create index if not exists admin_scrum_items_tracking_id_idx
  on public.admin_scrum_items (tracking_id);

drop trigger if exists set_admin_scrum_items_updated_at on public.admin_scrum_items;
create trigger set_admin_scrum_items_updated_at
before update on public.admin_scrum_items
for each row execute function public.set_updated_at();

alter table public.admin_scrum_items enable row level security;

drop policy if exists "Admins can manage scrum items" on public.admin_scrum_items;
create policy "Admins can manage scrum items"
  on public.admin_scrum_items
  for all
  using (private.is_admin())
  with check (private.is_admin());

grant select, insert, update, delete on public.admin_scrum_items to authenticated;
grant usage, select on sequence public.admin_scrum_items_tracking_number_seq to authenticated;
